# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: thinca/vim-themis
          path: vim-themis

      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1.3.5
        id: vim
        with:
          neovim: true
          version: stable

      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: xxd.vim

      - name: Run unit tests with themis.vim
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          cd xxd.vim
          ../vim-themis/bin/themis ./test
